/********************************************************************
* /home/daq/Desktop/s436/offline/s436_offline/G__FRSonline.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/daq/Desktop/s436/offline/s436_offline/G__FRSonline.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__FRSonline();
extern void G__cpp_setup_inheritanceG__FRSonline();
extern void G__cpp_setup_typetableG__FRSonline();
extern void G__cpp_setup_memvarG__FRSonline();
extern void G__cpp_setup_globalG__FRSonline();
extern void G__cpp_setup_memfuncG__FRSonline();
extern void G__cpp_setup_funcG__FRSonline();
extern void G__set_cpp_environmentG__FRSonline();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSUnpackProc.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/MWDCTracking.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSSortEvent.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSCalibrProc.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSUserEvent.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSSortProc.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSAnlProc.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSBasicProc.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSUserProc.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSUnpackEvent.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSCalibrEvent.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSAnalysis.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSParameter.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSData.h"
#include "/home/daq/Desktop/s436/offline/s436_offline/TFRSAnlEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__FRSonlineLN_TClass;
extern G__linked_taginfo G__G__FRSonlineLN_TBuffer;
extern G__linked_taginfo G__G__FRSonlineLN_TMemberInspector;
extern G__linked_taginfo G__G__FRSonlineLN_TObject;
extern G__linked_taginfo G__G__FRSonlineLN_TNamed;
extern G__linked_taginfo G__G__FRSonlineLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__FRSonlineLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FRSonlineLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__FRSonlineLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4EventElement;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4EventSource;
extern G__linked_taginfo G__G__FRSonlineLN_TH1;
extern G__linked_taginfo G__G__FRSonlineLN_TH1F;
extern G__linked_taginfo G__G__FRSonlineLN_TH1I;
extern G__linked_taginfo G__G__FRSonlineLN_TH2;
extern G__linked_taginfo G__G__FRSonlineLN_TH2I;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4Condition;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4WinCond;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4PolyCond;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4CondArray;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4Picture;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4Parameter;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4MbsEvent;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4EventProcessor;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSBasicProc;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSUnpackEvent;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4MbsSubEvent;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSUnpackProc;
extern G__linked_taginfo G__G__FRSonlineLN_TTree;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSSortProc;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4FileSource;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSSortEvent;
extern G__linked_taginfo G__G__FRSonlineLN_TRandom;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TMWParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TTPCParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TMWDCParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TMUSICParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TSCIParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TIDParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TSIParameter;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSCalibrEvent;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSCalibrProc;
extern G__linked_taginfo G__G__FRSonlineLN_TFile;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSUserProc;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSUserEvent;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSAnlEvent;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSAnlProc;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4CommandReceiver;
extern G__linked_taginfo G__G__FRSonlineLN_TGo4Analysis;
extern G__linked_taginfo G__G__FRSonlineLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__FRSonlineLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__FRSonlineLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSData;
extern G__linked_taginfo G__G__FRSonlineLN_TFRSAnalysis;

/* STUB derived class for protected member access */
